apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: db
  labels:
    environment: intern
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
#      volumes:
#        - name: vol
#          nfs:
#            server: 192.168.213.2
#            path: /mnt/data/sql
      containers:
        - name: mysql
          image: mysql:8.0
#          volumeMounts:
#            - name: vol
#              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-passwd