apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-conf
  namespace: turn
data:
  coturn.conf: |
    log-file=stdout
    relay-ip=192.168.213.2
    listening-port=5349
    min-port=49160
    max-port=49200
    use-auth-secret
    static-auth-secret=...
    realm=turn.domain.tld:5349
    no-cli
    cert=/var/run/secret/certs/turn.domain.tld.crt
    pkey=/var/run/secret/private/turn.domain.tld.key