apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dashboard.yaml
  - deployment.yaml
  - http.yaml
  - https.yaml
  - ingressroute.yaml
  - rbac.yaml
  - tls.yaml

secretGenerator:
  - name: ovh-token
    namespace: traefik
    literals:
      - app-key=...
      - app-secret=...
      - consumer-key=...