apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak
  namespace: teamspeak
  labels:
    environment: extern
    app: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamspeak
  template:
    metadata:
      labels:
        app: teamspeak
    spec:
      hostNetwork: true
      volumes:
        - name: vol
          nfs:
            server: 192.168.213.2
            path: /mnt/data/ts3
      containers:
        - name: teamspeak
          image: teamspeak
          volumeMounts:
            - name: vol
              mountPath: /var/ts3server
          ports:
            - containerPort: 9987
              name: tcp
            - containerPort: 10011
              name: udp
            - containerPort: 30033
              name: two
          env:
#            - name: TS3SERVER_DB_PLUGIN
#              value: "ts3db_mariadb"
#            - name: TS3SERVER_DB_SQLCREATEPATH
#              value: "create_mariadb"
#            - name: TS3SERVER_DB_HOST
#              value: "192.168.213.2:30306"
#            - name: TS3SERVER_DB_USER
#              value: "root"
#            - name: TS3SERVER_DB_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  key: password
#                  name: db-passwd
#            - name: TS3SERVER_DB_NAME
#              value: "teamspeak"
#            - name: TS3SERVER_DB_WAITUNTILREADY
#              value: "30"
            - name: TS3SERVER_LICENSE
              value: "accept"