apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    environment: extern
    app: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.conf.all.src_valid_mark
            value: "1"
      volumes:
        - name: vol
          nfs:
            server: 192.168.213.2
            path: /mnt/data/wireguard
        - name: mod
          nfs:
            server: 192.168.213.2
            path: /mnt/data/mod
      containers:
        - name: wireguard
          image: linuxserver/wireguard
          volumeMounts:
            - name: vol
              mountPath: /config
            - name: mod
              mountPath: /lib/modules
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          ports:
            - containerPort: 51820
              name: vpn
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
            - name: SERVERURL
              value: "vpn.domain.tld"
            - name: SERVERPORT
              value: "51820"