apiVersion: v1
kind: Service
metadata:
  name: wireguard-service
  namespace: wireguard
  labels:
    environment: extern
    app: wireguard
spec:
  selector:
    app: wireguard
  type: ClusterIP
  ports:
    - targetPort: 51820
      port: 51820
      name: vpn
