global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'shome'
    scrape_interval: 60s
    metrics_path: /api/prometheus
    # Long-Lived Access Token
    bearer_token: ''
    scheme: https
    static_configs:
      - targets: ['shome.domain.tld']

  - job_name: 'k3s'
    static_configs:
      - targets: ['192.168.213.2:9100']

  - job_name: 'OPNsense'
    static_configs:
      - targets: [ '192.168.213.1:9273', '192.168.213.1:9100' ]

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.kube-system:8080']

  - job_name: 'core-dns'
    static_configs:
      - targets: ['kube-dns.kube-system:9153']

  - job_name: 'cadvisor'
    scheme: https
    metrics_path: /api/v1/nodes/k3s-main/proxy/metrics/cadvisor
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    basic_auth:
      username: admin
      password: passwd
    static_configs:
      - targets: ['192.168.213.2:6443']

  - job_name: 'apiserver'
    scheme: https
    metrics_path: /api/v1/nodes/k3s-main/proxy/metrics
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    basic_auth:
      username: admin
      password: passwd
    static_configs:
      - targets: ['192.168.213.2:6443']

  - job_name: 'TRAEFIK'
    static_configs:
     - targets: ['traefik.traefik:8100']

  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.213.10  # SNMP device.
       #- 192.168.213.254
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-service.mon:9116  # The SNMP exporter's real hostname:port.
